services:

  database:
    build: "database"
    environment:
      - POSTGRES_PASSWORD=pwd
    volumes:
      - db-volume:/var/lib/postgresql/data
    networks:
      - my-net

  simple-api:
    build: "simple-api"
    environment:
      - DATABASE_HOST=database
      - DATABASE_PASSWORD=pwd
    networks:
      - my-net

  httpd:
    build: "http-server"
    ports:
      - "80:80"
    networks:
      - my-net

networks:
  my-network:

volumes:
  db-volume :