name: Deploy with Ansible

on:
  workflow_run:
    workflows: ["CI devops 2025"]  # nom exact du workflow main.yml
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - name: Install Ansible
        run: |
          python -m pip install --upgrade pip
          pip install ansible
      - name: Add SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H yanis-mehdi.hocine.takima.cloud >> ~/.ssh/known_hosts
      - name: Test SSH Connection
        run: |
          ssh -i ~/.ssh/id_rsa -o StrictHostKeyChecking=no admin@yanis-mehdi.hocine.takima.cloud "echo ✅ Connexion SSH réussie"
      - name: Vérification clé publique sur le serveur
        run: |
          PUB_KEY=$(ssh-keygen -y -f ~/.ssh/id_rsa)
          ssh -i ~/.ssh/id_rsa admin@yanis-mehdi.hocine.takima.cloud "grep \"$PUB_KEY\" ~/.ssh/authorized_keys && echo '✅ Clé publique trouvée sur le serveur'"
      - name: Debug Key + Inventory
        working-directory: ansible
        run: |
          echo "Inventory content:"
          cat inventories/setup.yml
          echo "---"
          echo "Private key content (first 5 lines):"
          head -n 5 ~/.ssh/id_rsa
          echo "Line endings in inventory:"
          file inventories/setup.yml
 
      - name: Run Ansible Playbook
        working-directory: ansible
        run: |
          ansible-playbook -i inventories/setup.yml playbook.yml --private-key=/home/runner/.ssh/id_rsa




